### ISSUE TITLE
Using .orEmpty() for nullable lists

### ISSUE THREAD

**Issue by StylianosGakis** [mitchtabian/MVVMRecipeApp#1]
https://github.com/mitchtabian/MVVMRecipeApp/blob/196b126f9f2e7e8540fb0e32444f6d228318e78c/app/src/main/java/com/codingwithmitch/mvvmrecipeapp/network/model/RecipeNetworkMapper.kt#L19

It'd be nice to replace the `?: ListOf` with `.orEmpty()` as suggested here as well https://twitter.com/kotlin/status/1337306632477356034?s=20.

It just removes some ambiguity for someone maybe not so familiar with the `?:` Kotlin syntax. Totally a preference though, I just thought it'd be nice to let you know this exists.

**Comment by mitchtabian** [comment]
Sure I'll do that in next video.
